#!/cwm/sbin/sh
#  
# Made by ANT, Date: 08/13/2012
#  

# if external SD is not present then CWM will use internal SD
if /cwm/sbin/[ ! -e /dev/block/mmcblk1p1 ]
then
  /cwm/sbin/mv -f /cwm/system/etc/no_sdcard.fstab /cwm/system/etc/recovery.fstab
else
  /cwm/sbin/rm /cwm/system/etc/no_sdcard.fstab
fi

#kill stock adbd in order to replace it
/cwm/sbin/killall adbd
# copy CWM files to ramdisk
/cwm/sbin/cp -R /cwm/* /

# execute CWM recovery
/sbin/recovery
